version: "3"
services:
  masternode:
    image: kunstmaan/base-multichain
    environment:
      - CHAINNAME=dockerchain
      - PARAM_CONNECT='anyone-can-connect|true'
      - PARAM_MINE='anyone-can-mine|true'
      - RPC_USER=rpcuser
      - RPC_PASSWORD=rpcpassword
      - RPC_ALLOW_IP=172.27.0.0/16
    volumes:
      - ./runchain_caliper_master.sh:/root/runchain_new.sh
      - ./node-files/dockerchain:/root/.multichain
    command: bash /root/runchain_new.sh
    ports:
        - "1000:7447"
        - "999:8000"

  slavenode1:
    image: kunstmaan/base-multichain
    environment:
      - CHAINNAME=dockerchain
      - RPC_USER=rpcuser
      - RPC_PASSWORD=rpcpassword
      - RPC_ALLOW_IP=172.27.0.0/16
      - RPC_PORT=5999
    volumes:
      - ./runchain_caliper_slave1.sh:/root/runchain_new.sh
      - ./node-files/dockerchain-slave1:/root/.multichain
    command: bash /root/runchain_new.sh
    ports:
        - "2000:7447"
        - "1999:8000"
    depends_on:
      - masternode