version: "3"
services:
  masternode:
    image: amolpednekar/multichain_node:v1
    environment:
      - CHAINNAME=dockerchain
    volumes:
      - ./node-scripts/runchain_caliper_master.sh:/root/runchain.sh
      - ./server:/root/server
    #  - ./node-files/dockerchain:/root/.multichain
    command: bash /root/runchain.sh
    ports:
      - "1000:1447"
      - "999:1448"

  slavenode1:
    image: amolpednekar/multichain_node:v1
    environment:
      - CHAINNAME=dockerchain
    volumes:
      - ./node-scripts/runchain_caliper_slave1.sh:/root/runchain.sh
      - ./node-scripts/multichain_slave1.conf:/root/.multichain/dockerchain/multichain.conf
      - ./server:/root/server
    command: bash /root/runchain.sh
    ports:
      - "2000:2447"
      - "1999:2448"
    depends_on:
      - masternode
            
  slavenode2:
    image: amolpednekar/multichain_node:v1
    environment:
      - CHAINNAME=dockerchain
    volumes:
      - ./node-scripts/runchain_caliper_slave2.sh:/root/runchain.sh
      - ./node-scripts/multichain_slave2.conf:/root/.multichain/dockerchain/multichain.conf
      - ./server:/root/server
    command: bash /root/runchain.sh
    ports:
      - "3000:3447"
      - "2999:3448"    
    depends_on:
      - masternode