version: "3"
services:
  slavenode1:
    image: kunstmaan/base-multichain
    environment:
      - CHAINNAME=dockerchain
    volumes:
      - ./runchain_caliper_slave1.sh:/root/runchain_new.sh
      - ./node-files/dockerchain-slave1:/root/.multichain
      - ./multichain.conf:/root/.multichain/dockerchain/multichain.conf
    command: bash /root/runchain_new.sh
    ports:
        - "2000:5000"
        - "1999:4999"