version: "3"
services:
  masternode:
    image: kunstmaan/base-multichain
    environment:
      - CHAINNAME=dockerchain
    volumes:
      - ./runchain_caliper_master.sh:/root/runchain_new.sh
      - ./node-files/dockerchain:/root/.multichain
    command: bash /root/runchain_new.sh
    ports:
        - "1000:1447"
        - "999:1448"
        
  slavenode1:
    image: kunstmaan/base-multichain
    environment:
      - CHAINNAME=dockerchain
    volumes:
      - ./runchain_caliper_slave1.sh:/root/runchain_new.sh
      - ./multichain1.conf:/root/.multichain/dockerchain/multichain.conf
      - ./node-files/dockerchain-slave1:/root/.multichain
    command: bash /root/runchain_new.sh
    ports:
      - "2000:2447"
      - "1999:2448"
            
  slavenode2:
    image: kunstmaan/base-multichain
    environment:
      - CHAINNAME=dockerchain
    volumes:
      - ./runchain_caliper_slave2.sh:/root/runchain_new.sh
      - ./multichain2.conf:/root/.multichain/dockerchain/multichain.conf
      - ./node-files/dockerchain-slave2:/root/.multichain
    command: bash /root/runchain_new.sh
    ports:
      - "3000:3447"
      - "2999:3448"