version: "3"
services:
  masternode:
    image: amolpednekar/multichain_node:v1
    environment:
      - CHAINNAME=dockerchain
    volumes:
      - ../node-scripts/runchain_caliper_master.sh:/root/runchain.sh
      - ../server:/root/server
    #  - ./node-files/dockerchain:/root/.multichain
    command: bash /root/runchain.sh
    ports:
      - "1000:1000"
      - "999:999"