version: "3"
services:
  masternode:
    container_name: masternode
    image: amolpednekar/multichain:v1.0.4
    environment:
      - CHAINNAME=dockerchain
      - EVENT_LISTENER_IP=10.244.48.72
    #  - EVENT_LISTENER_IP=10.244.51.108
    volumes:
      - ../node-scripts/runchain_caliper_master.sh:/root/runchain.sh
      - ../server:/root/server
      #- ../node-data/dockerchain:/root/.multichain
    command: bash /root/runchain.sh
    ports:
      - "1000:1000"
      - "999:999"